name: Setup Sandbox Build
description: Install KVM, QEMU, Lima, and sandbox CLI for VM builds

inputs:
  sandbox-cli-token:
    description: GitHub token for downloading sandbox CLI
    required: true

runs:
  using: composite
  steps:
    - name: Enable KVM
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Install build dependencies
      shell: bash
      run: |
        set -ex
        sudo apt-get update
        sudo apt-get install -y qemu-utils qemu-system-x86

        LIMA_VERSION=$(curl -s https://api.github.com/repos/lima-vm/lima/releases/latest | jq -r '.tag_name')
        curl -fsSL "https://github.com/lima-vm/lima/releases/download/${LIMA_VERSION}/lima-${LIMA_VERSION#v}-Linux-x86_64.tar.gz" | sudo tar -xz -C /usr/local
        curl -fsSL "https://github.com/lima-vm/lima/releases/download/${LIMA_VERSION}/lima-additional-guestagents-${LIMA_VERSION#v}-Linux-x86_64.tar.gz" | sudo tar -xz -C /usr/local

    - name: Install sandbox CLI
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.sandbox-cli-token }}
      run: |
        set -ex
        gh release download --repo LF-Certification/sandbox-building-service \
          --pattern 'sandbox_*_linux_amd64.tar.gz' \
          --output /tmp/sandbox.tar.gz
        tar -xzf /tmp/sandbox.tar.gz -C /tmp
        sudo mv /tmp/sandbox /usr/local/bin/
        sudo chmod +x /usr/local/bin/sandbox
        sandbox version
